<a href="https://colab.research.google.com/github/aarpitdubey/AdvanceAnalytics_edwisorDatascience/blob/master/04_Assignment_Introduction_to_Lists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <u>While doing this assignment only use those concepts which have been taught till now</u>

## <u>Problem 1</u>

A list contains the average daily temperature(in degree Celsius) of a city over a particular week. Write a Python code to swap the highest and the lowest temperatures

In [1]:
# A list containing average daily temperature over a week 
temperatures = [34, 40, 29, 33, 42, 37, 39 ]

# The expected output 
# output_temperatures = [34, 40, 42, 33, 29, 37, 39]

In [2]:
# Store the highest temperature
max_temp = max(temperatures)

# Index of the element with the highest temperature
max_temp_index = temperatures.index(max_temp)

In [3]:
# Store the lowest temperature 
min_temp = min(temperatures)

# Index of the element with the lowest temperature
min_temp_index = temperatures.index(min_temp)

In [4]:
# Swap the highest and the lowest temperatures
temperatures[max_temp_index] = min_temp
temperatures[min_temp_index] = max_temp

In [5]:
# Print the output list
print(temperatures)

[34, 40, 42, 33, 29, 37, 39]



## <u>Problem 2 </u>

### Measures of Averages

* Mean of a group is defined as the sum of the elements in the group divided by the number of elements in the group.
* Median is the middle number in a <b>sorted</b>, ascending or descending, list of numbers. If the list has $N$ numbers where $N$ is odd, then median is the element in the middle i.e, $(\frac{N+1}{2})^{th}$ element. If $N$ is even, then median is the mean of $(\frac{N}{2})^{th}$ and $(\frac{N}{2}+1)^{th}$ elements

In [6]:
# List of product prices

prod_price_list = [400, 250, 800, 550, 600, 820, 720, 15000, 360,250]

In [7]:
# Calculate the mean of the product prices. Use list functions. Also print the mean_price
def mean_(lst):
  return sum(lst)//len(lst)

mean_price = mean_(prod_price_list)
print(mean_price)

1975


### Calculate the median price

In [8]:
# Step 1 - Obtain the sorted list. Print the sorted_prices
def median_(lst):
  if len(lst) % 2 == 1:
    return lst[((len(lst)+1)//2)+1]
  else:
    return (lst[(len(lst)//2)-1] + lst[((len(lst)//2) + 1)-1]) // 2

sorted_prices = sorted(prod_price_list)
print(sorted_prices)

[250, 250, 360, 400, 550, 600, 720, 800, 820, 15000]


In [9]:
# Check if the number of elements in the list is even or odd
print("even") if len(prod_price_list)%2==0 else print("odd")

even


In [10]:
# Use the corresponding formula to calculate the median and print the median
median_price = median_(sorted_prices)
print(median_price)

575


In [11]:
# Check which is greater, mean or median
f"mean_price = {mean_price}, is greator than median_price {median_price}"if mean_price >= median_price else f"median_price = {median_price}, is greator than mean_price {mean_price}"

'mean_price = 1975, is greator than median_price 575'

### Why do you think that is the case??

### <u>Write your explanation in this text cell</u>

Your explanation :  As, we can seen in the sorted list: [250, 250, 360, 400, 550, 600, 720, 800, 820, 15000], most of the element lies in between 200 to 900 but the last element of our sorted list is **15000 which is too high in compare to other element of the same list**. I think it is an **unwanted, unexpected and, outlier** in the list which makes the mean_price greator than the median_price.

## <u> Problem 3 </u>

Having a nested list sometimes might be a bit problematic. An individual was asked to collect the names of companies in the technology sector. While creating the list, by mistake the last three companies were subsumed in a list as shown below. You are required to get rid of the nesting

In [12]:
# The list of tech companies curated by the individual
tech_companies = ['Qualcomm','Google','Apple',['Nvidia','Cisco','Samsung']]

# The final list that we want
# correct_tech_companies = ['Qualcomm','Google','Apple','Nvidia','Cisco','Samsung']

In [13]:
# Write your code below
sublist = tech_companies[3]
tech_companies = [ele for ele in tech_companies if ele!=sublist]
tech_companies += sublist # Concatenation of list
print(tech_companies)

['Qualcomm', 'Google', 'Apple', 'Nvidia', 'Cisco', 'Samsung']


In [14]:
# The list of tech companies curated by the individual
tech_companies = ['Qualcomm','Google','Apple',['Nvidia','Cisco','Samsung']]

# The final list that we want
# correct_tech_companies = ['Qualcomm','Google','Apple','Nvidia','Cisco','Samsung']

# Do the same task another way
popout_list = tech_companies.pop(3)
tech_companies.extend(popout_list)
print(tech_companies)


['Qualcomm', 'Google', 'Apple', 'Nvidia', 'Cisco', 'Samsung']
